# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
# CodeRabbit Configuration for Nextcloud Sentinel

language: "fr-CA"

reviews:
  # Review profile - assertive gives more thorough feedback
  profile: "assertive"

  # Generate PR summary
  high_level_summary: true

  # Request changes vs comments
  request_changes_workflow: true

  # Enable automatic reviews on PRs
  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - master

  # Ignore generated/vendor files (moved here from root level)
  path_filters:
    - "!**/node_modules/**"
    - "!**/build/**"
    - "!**/.git/**"
    - "!**/translations/**"

  # Focus areas for Kill Switch code
  path_instructions:
    - path: "src/libsync/killswitch/**"
      instructions: |
        This is the Kill Switch anti-ransomware module. Pay special attention to:
        - Security vulnerabilities
        - False positive/negative detection rates
        - Performance impact on sync operations
        - Thread safety
    - path: "test/**"
      instructions: |
        Test files. Ensure good coverage and meaningful assertions.

chat:
  auto_reply: true
